DROP TABLE IF EXISTS PLAYERS CASCADE;
DROP TABLE IF EXISTS RESULTS CASCADE;
DROP TABLE IF CARDS CASCADE;
DROP TABLE IF SYMBOLS CASCADE;

CREATE TABLE PLAYERS(
  EMAIL varchar(40) PRIMARY KEY,
  PASSWORD varchar(200)
);

CREATE TABLE RESULTS(
  ID SERIAL PRIMARY KEY,
  USER_ID varchar(40) NOT NULL,
  GAME_TIME TIME NOT NULL
);

CREATE TABLE 





